---
# Tasks to collect virtual environment metadata
- name: Collect venv metadata
  delegate_to: "{{ target_host }}"
  block:
    - name: Get pip freeze output
      shell: |
        source {{ actual_venv_path }}/bin/activate
        pip freeze
      register: pip_freeze_output
      changed_when: false

    - name: Get ansible version
      shell: |
        source {{ actual_venv_path }}/bin/activate
        ansible --version
      register: ansible_version_output
      changed_when: false

    - name: List installed collections
      shell: |
        source {{ actual_venv_path }}/bin/activate
        ansible-galaxy collection list --format json 2>/dev/null || echo '{}'
      register: collections_output
      changed_when: false

    - name: Get Python version
      shell: |
        {{ actual_venv_path }}/bin/python --version
      register: python_version_output
      changed_when: false

    - name: Get venv size
      shell: |
        du -sh {{ actual_venv_path }} | cut -f1
      register: venv_size_output
      changed_when: false

    - name: Create metadata structure
      set_fact:
        venv_metadata:
          venv_name: "{{ venv_name }}"
          venv_path: "{{ actual_venv_path }}"
          created_at: "{{ ansible_date_time.iso8601 }}"
          target_host: "{{ target_host }}"
          persistent: "{{ persist_venv }}"
          python_version: "{{ python_version_output.stdout }}"
          ansible_version: "{{ ansible_version_output.stdout_lines }}"
          pip_packages: "{{ pip_freeze_output.stdout_lines }}"
          ansible_collections: "{{ collections_output.stdout | from_json }}"
          venv_size: "{{ venv_size_output.stdout }}"

    - name: Return metadata to iOS app
      debug:
        var: venv_metadata