---
# Tasks to execute a playbook within the virtual environment
- name: Execute playbook in virtual environment
  delegate_to: "{{ target_host }}"
  block:
    - name: Create playbooks directory in venv
      file:
        path: "{{ actual_venv_path }}/playbooks"
        state: directory
        mode: '0755'
      when: playbook_to_run is defined

    - name: Copy playbook to venv playbooks directory
      copy:
        src: "{{ playbook_to_run }}"
        dest: "{{ actual_venv_path }}/playbooks/{{ playbook_to_run | basename }}"
        mode: '0644'
      when: playbook_to_run is defined
      register: copied_playbook

    - name: Set playbook path within venv
      set_fact:
        remote_playbook_path: "{{ actual_venv_path }}/playbooks/{{ playbook_to_run | basename }}"

    - name: Debug ansible command
      debug:
        msg: "Executing: {{ actual_venv_path }}/bin/ansible-playbook {{ remote_playbook_path }} -i localhost, -c local"

    - name: Execute playbook
      command:
        argv:
          - "{{ actual_venv_path }}/bin/ansible-playbook"
          - "{{ remote_playbook_path }}"
          - "-i"
          - "localhost,"
          - "-c"
          - "local"
      environment: "{{ playbook_environment | default({}) | combine({'ANSIBLE_COLLECTIONS_PATH': actual_venv_path + '/ansible_collections'}) }}"
      register: playbook_output

    - name: Display playbook output
      debug:
        var: playbook_output.stdout_lines

    - name: Cleanup copied playbook
      file:
        path: "{{ remote_playbook_path }}"
        state: absent
      when: 
        - copied_playbook is defined
        - copied_playbook.changed