repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3

  - repo: local
    hooks:
      - id: flake8
        name: Flake8 in briefcase_ansible_test
        entry: sh -c 'cd briefcase_ansible_test && python -m flake8 "${@#briefcase_ansible_test/}"; exit $?' --
        language: system
        types: [python]
        files: ^briefcase_ansible_test/

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.389
    hooks:
      - id: pyright
        args: [--project, briefcase_ansible_test/pyproject.toml]
        additional_dependencies: [ocrmac, pillow, mcp, pytest]