[tool.pyright]
include = [
    "__init__.py",
    "process.py", 
    "queues.py",
    "synchronize.py",
    "context.py",
    "run_tests.py",
    "tests/"
]

exclude = [
    "dev/debug/",
    "dev/benchmarks/"
]

reportMissingImports = true
reportMissingTypeStubs = false
reportUnknownArgumentType = false
reportUnknownVariableType = false
reportUnknownMemberType = false

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''